import { BullModule, SharedBullAsyncConfiguration } from '@nestjs/bullmq';
import { DynamicModule, Module } from '@nestjs/common';

import { RepositoryPostgresModule, TrackedQueueRepository } from '@omedym/nestjs-dmq-repository';
import { NestjsLoggingModule, NestjsLogger, NestjsSentryModule, LoggerConfiguration } from '@omedym/nestjs-telemetry';

import { TrackedJobEventProcessor, TrackedJobEventQueue } from './queue';
import { Providers } from './providers';

/**
 * Provides support for TrackedQueue processors to publish job events to the
 * tracked job event queues. This is needed by any service/module that is hosts
 * an implementation of a tracked job processor.
 */
@Module({})
export class PublishTrackedQueueJobEventsModule {
  static forRootAsync(asyncBullConfig: SharedBullAsyncConfiguration, loggerConfig: LoggerConfiguration): DynamicModule {
    return {
      imports: [
        NestjsLoggingModule.forRoot(loggerConfig),
        NestjsSentryModule,
        BullModule.forRootAsync(asyncBullConfig),
        BullModule.registerQueueAsync({ name: Providers.TrackedJobEventQueue }),
      ],
      providers: [
        { provide: Providers.ILogger, useClass: NestjsLogger },
        TrackedJobEventQueue,
      ],
      exports: [
        Providers.ILogger,
        TrackedJobEventQueue
      ],
      module: PublishTrackedQueueJobEventsModule,
    }
  }
}

/**
 * Instantiates background processor for handling tracked job events generated by
 * tracked queue processors.
 */
@Module({})
export class ProcessTrackedQueueJobEventsModule {
  static forRootAsync(asyncBullConfig: SharedBullAsyncConfiguration, loggerConfig: LoggerConfiguration): DynamicModule {
    return {
      imports: [
        NestjsLoggingModule.forRoot(loggerConfig),
        NestjsSentryModule,
        BullModule.forRootAsync(asyncBullConfig),
        BullModule.registerQueueAsync({ name: Providers.TrackedJobEventQueue }),
        RepositoryPostgresModule,
      ],
      providers: [
        { provide: Providers.ILogger, useClass: NestjsLogger },
        TrackedJobEventQueue,
        TrackedJobEventProcessor,
        TrackedQueueRepository,
      ],
      module: ProcessTrackedQueueJobEventsModule,
    }
  }
}
